### ISSUE TITLE
Add "new version available" notification

### ISSUE THREAD

**Issue by DavidMStraub** [DavidMStraub/Gramps.js#10]
When a new version of the frontend (of the service worker) is available, it would be great to have a "new version available" notification. However I'm not sure how to do it.

**Comment by DavidMStraub** [comment]
Finally figured it out! :rocket: :relieved:

**Comment by khashashin** [comment]
I don't see this tag in `0.17.0` version and PRs, did you not implement this feature? Could I try it out?

**Comment by DavidMStraub** [comment]
Closed last year because it was implemented last year ... 

https://github.com/gramps-project/Gramps.js/blob/main/src/components/GrampsjsUpdateAvailable.js

Don't understand the question.
