### ISSUE TITLE
Locale in timeline view map

### ISSUE THREAD

**Issue by cdhorn** [DavidMStraub/Gramps.js#11]
Just noticed that United States on the timeline view map on my PC is displayed in both German and English as "Vereinigte Staaten von Amerika United States"

**Comment by DavidMStraub** [comment]
Was that before or after the commit a11f6da499fa1153ab7c938e7543fca4b9e42580?

**Comment by cdhorn** [comment]
Latest...
![Screenshot from 2020-12-31 07-59-53](https://user-images.githubusercontent.com/43528418/103411493-4a356180-4b3e-11eb-8386-5f510325e7e7.png)

**Comment by DavidMStraub** [comment]
Oh sorry, I missed that you were referring to the map. True, that's because I use the OSM-DE tiles (also for the big map view), which is not optimal for an international application...

**Comment by DavidMStraub** [comment]
Switched default tiles to CartoDB - mostly because they are prettier, but they also have English place names. That solves this issue, but has other disadvantages. In general, the only real solution is to build the frontend with different tile URLs as appropriate...
