### ISSUE TITLE
Password reset link sometimes only working after emptying cache

### ISSUE THREAD

**Issue by DavidMStraub** [DavidMStraub/Gramps.js#14]

**Comment by windmark** [comment]
Hi @DavidMStraub I have a question related to the password reset link and thought it could fit to this issue. It could also fit the gramps-webapi repo, not sure.

My gramps-webapi has been set up and successfully emails the password reset link. However, when clicking the link I'm met by an empty front page with only the menu. I'm logged in, sure, but there is nowhere to actually change the password. What is the expected view at this point? The response is a 200 with the content below.

<details>
<summary>Response content</summary>

<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="description" content="Gramps.js Genealogical Research Web App"><base href="/"><link rel="preconnect" href="https://fonts.gstatic.com"><link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500;1,600&amp;display=swap" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100;200;300;400;500&amp;display=swap" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500&amp;display=swap" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100;200;300;400;500&amp;display=swap" rel="stylesheet"><link href="https://fonts.googleapis.com/css?family=Material+Icons&amp;display=block" rel="stylesheet"><link rel="icon" href="images/favicon.ico"><link rel="manifest" href="manifest.json"><meta name="theme-color" content="#6D4C41"><meta name="mobile-web-app-capable" content="yes"><meta name="application-name" content="Gramps"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar" content="#6D4C41"><meta name="apple-mobile-web-app-title" content="Gramps"><link rel="apple-touch-icon" href="images/manifest/icon-48x48.png"><link rel="apple-touch-icon" sizes="72x72" href="images/manifest/icon-72x72.png"><link rel="apple-touch-icon" sizes="96x96" href="images/manifest/icon-96x96.png"><link rel="apple-touch-icon" sizes="144x144" href="images/manifest/icon-144x144.png"><link rel="apple-touch-icon" sizes="192x192" href="images/manifest/icon-192x192.png"><style>body,html{margin:0;padding:0;height:100%}</style><title>gramps-js</title><link rel="preload" href="./a8a51968.js" as="script" crossorigin="anonymous"></head><body><gramps-js></gramps-js><script type="module" src="./a8a51968.js"></script><script>"serviceWorker"in navigator&&window.addEventListener("load",(function(){navigator.serviceWorker.register("sw.js").then((function(){console.log("ServiceWorker registered.")})).catch((function(e){console.log("ServiceWorker registration failed: ",e)}))}))</script></body></html>

</details>

Furthermore, I'm getting 401 from the /metadata and /translations at this stage.

**Comment by DavidMStraub** [comment]
Something showing in your console (F12)?

**Comment by windmark** [comment]
> Something showing in your console (F12)?

See the screenshots below. I'm getting a 200 with the response in my post above. This time around I'm met with a not logged in error and it doesn't seem like the access tokens are correctly set. 

What behavior are you experiencing? 

![Chrome Network Console](https://user-images.githubusercontent.com/3810163/103576677-ced40700-4ed3-11eb-81b8-d98d0e7a3686.png)


![Console Output](https://user-images.githubusercontent.com/3810163/103576382-566d4600-4ed3-11eb-9064-8a9559fcc353.png)

**Comment by DavidMStraub** [comment]
I'm confused; do you see the login form or are you logged in and only see the menu?

It's not clear to me whether you are having a problem with the frontend or the backend. Can you please try whether fetching a token etc. works when just using `curl` with the backend?

By the way, the password reset link is *not* supposed to show Gramps.js at all. It is supposed to show an HTML form that is directly provided by the backend. Can you try pasting the reset link into a private browser tab?

**Comment by windmark** [comment]
Ah I see, I thought it was Gramps.js displaying it based on the jwt token.

It does indeed work when running in incognito mode (or simply deleting the Site Data in Chrome). It seems like if I deregister and stop the Service Worker it works. As soon as I have one running I'm met with the Login page and not the Update Password page.

**Comment by DavidMStraub** [comment]
Thanks for investigating and confirming that bug! Now if only I knew how to fix it... unfortunately I am quite ignorant about how the service worker actually works...

**Comment by DavidMStraub** [comment]
I believe this is now fixed in `main` (the trick was to exclude `/api/` from workbox's `NavigateFallback`), but it would be great if somebody could confirm that.

**Comment by windmark** [comment]
> I believe this is now fixed in `main` (the trick was to exclude `/api/` from workbox's `NavigateFallback`), but it would be great if somebody could confirm that.

Hi @DavidMStraub I finally had some time over to check this on my deployment and #14 indeed seems to have solved the issue. Thank you!

**Comment by DavidMStraub** [comment]
Great, thanks for checking!
