### ISSUE TITLE
Link demo instance from Readme

### ISSUE THREAD

**Issue by azzamsa** [DavidMStraub/Gramps.js#16]
Hi.

Could we have [a demo instance](https://github.com/DavidMStraub/gramps-webapp#demo) like it's in the old days?

I see [this line](https://github.com/DavidMStraub/Gramps.js/blob/032377d47dbe164f68ab8804b57c7037a2ac9016/.github/workflows/pages.yml#L17). But I just get the blank page.

Thank you for maintaining GrampsWeb. It is been a while. Surprised that it's already under the official gramps organization. Kudos!

---

Btw, I can't find the context. where the conversation starts. asking it to be adopted by the official. I just find [this issue](https://github.com/DavidMStraub/gramps-webapp/issues/35). Or maybe you are already a member of the gramps project?

**Comment by DavidMStraub** [comment]
Hi!

> Could we have a demo instance like it's in the old days?

Oops, apparently I forgot to link the Demo instance from the readme, it's here: https://davidmstraub.github.io/Gramps.js/
The URL in the Github workflow you linked is the backend (the REST API).

There are some known issues with it due to the frontend being hosted on Github pages, like #15 (feel free to add other issues you might observe).

> Thank you for maintaining GrampsWeb. It is been a while. Surprised that it's already under the official gramps organization. Kudos!

We implemented the REST API at https://github.com/gramps-project/gramps-webapi/, which serves as a backend for the Gramps.js web app (but could also be used for other apps) and which is an "official" project. The frontend (Gramps.js) is currently not under the official Gramps organization.

**Comment by azzamsa** [comment]
What to put in `set home person`. I can't select anything:

![image](https://user-images.githubusercontent.com/17734314/110243677-fc016c00-7f8d-11eb-9624-d4bcbaa41620.png)


---

> We implemented the REST API at gramps-project/gramps-webapi, which serves as a backend for the
> Gramps.js web app (but could also be used for other apps) and which is an "official" project. The 
> frontend (Gramps.js) is currently not under the official Gramps organization.

I see. I mean, I have followed `gramps-webapp` since it's in `DavidMStraub /gramps-webapp` in ~2019.
I am surprised that it is now under `gramps-project/gramps-webapi`. I mean, I can't find any issue regarding the request of the Official Gramps maintainer to asking `gramps-webapp` to be adopted under their organization. Are they asking you directly via email or something?

**Comment by DavidMStraub** [comment]
> What to put in set home person. I can't select anything:

When you start typing in the field, a drop-down list should appear. Does that work?

> I am surprised that it is now under gramps-project/gramps-webapi. I mean, I can't find any issue regarding the request of the Official Gramps maintainer to asking gramps-webapp to be adopted under their organization. Are they asking you directly via email or something?

It basically started with this discussion:
https://gramps.discourse.group/t/web-based-gramps/225/1

**Comment by azzamsa** [comment]
> It basically started with this discussion:
> gramps.discourse.group/t/web-based-gramps/225/1

Thanks for the link. I am very happy now it's under official repository.

> When you start typing in the field, a drop-down list should appear. Does that work?

I can't select the drop-down:

![gramps](https://user-images.githubusercontent.com/17734314/110244616-26552880-7f92-11eb-9b31-6f6689882b3e.gif)

**Comment by DavidMStraub** [comment]
It does say "Selected: Abraham Douglas". Just click "Complete". Not very intuitive UI, I admit!

**Comment by azzamsa** [comment]
works great.

I think we need to improve its responsiveness.

![image](https://user-images.githubusercontent.com/17734314/110424483-78529700-80d5-11eb-87d0-37ccd709398d.png)
