### ISSUE TITLE
Maps on a phone

### ISSUE THREAD

**Issue by emyoulation** [DavidMStraub/Gramps.js#17]
Getting a weird display (on an Android phone In Chrome) after setting home person to I0044 and scrolling...
![Screenshot_20210708-145741](https://user-images.githubusercontent.com/69127217/124984159-7dc9da80-dffe-11eb-856a-9c634580ab31.png)
This is in landscape mode but portrait is similar.

**Comment by DavidMStraub** [comment]
You're right, I'm also seeing this on desktop, but not sure why. It doesn't happen on my own, private deployment. Perhaps we're hitting some rate limits that OSM is imposing...

**Comment by emyoulation** [comment]
Interesting! Did you notice the slight vertical misalignments of the tiles that do appear? That seems more significant than tiles that are not filling in or the broken image markers.

**Comment by DavidMStraub** [comment]
Found out this is the same bug as #15 - it doesn't find the leaflet.css where it expects to.

**Comment by DavidMStraub** [comment]
This should be fixed now!

**Comment by emyoulation** [comment]
Has the demo instance been refreshed? I just logged into 
https://mysterious-cove-02458.herokuapp.com/ 
and it had broken image links for ALL tiles now.

And chrome griped about the test user/pw combo being used in a databreach

**Comment by DavidMStraub** [comment]
That's the wrong demo, please try https://davidmstraub.github.io/Gramps.js/

**Comment by emyoulation** [comment]
That site is thoroughly broken. 404 pages everywhere but the landing page

**Comment by DavidMStraub** [comment]
Can you please try again https://davidmstraub.github.io/Gramps.js/ doing a Ctrl + F5 and then clicking on the Maps menu item. I'm still in the process of solving #15 so many links don't work, but the map should work now.

**Comment by emyoulation** [comment]
Using Chrome on an Android phone. No Ctrl key. But can use a drag down to force a refresh 

Ok. Now that just plain weird....
Anytime I force a refresh on any page, it throws a a 404 error. But browsing through the hotlinks (mostly) works.  

And the map tiling works that way too

**Comment by DavidMStraub** [comment]
Ok great, thanks for checking. So this one can be closed. The remaining issues are due to #15 and will be fixed tonight...
