### ISSUE TITLE
Feature - Family tree vertically

### ISSUE THREAD

**Issue by Princeofthebow** [DavidMStraub/Gramps.js#18]
Congratulations on this work it looks really good. I'm planning to adopt it as a way to distribute the family tree work I have done for family!

I though do have a feature to ask for: would it be possible to show the family tree vertically rather the horizontally? Meaning that the the tree grows from the top to the bottom of the screen? This would be important as an option as when (some) people of previous generations look at it they find it more handy to do it in a vertical fashion.

Perhaps also increase the # of generations?

**Comment by DavidMStraub** [comment]
Thanks!

Yes, making it vertical should be possible, but I was too lazy to do it so far. I am dreaming (actually, already partially implemented) a tree view using Gramps-generated Graphviz SVGs, that would also be vertical.

> Perhaps also increase the # of generations?

Did you notice the slider? The max is currently 6, where it becomes anyway hardly usable, and the size of the data to be fetched increases exponentially...

**Comment by DavidMStraub** [comment]
Having fun with my Graphviz-based implementation. I'm leaning towards having two tree views: the existing one and the Graphviz one which is vertical. Teaser:

<img width="954" alt="grafik" src="https://user-images.githubusercontent.com/10965193/135730823-de91b0b1-19a2-4519-a863-75fcabbf6052.png">

**Comment by DavidMStraub** [comment]
Can be seen in action now here: https://grampsjs-demo.herokuapp.com/graph

Just not integrated into the navigation yet.

**Comment by DavidMStraub** [comment]
This is now integrated (see https://grampsjs-demo.herokuapp.com/tree) based on Graphviz including zoom (buttons, mouse wheel or touch pinch) and panning support. I think this can be closed!

**Comment by dror3go** [comment]
New Gramps web user here :wave: 
@DavidMStraub What ever happened to this vertical view? IS it available somehow by config?

**Comment by DavidMStraub** [comment]
It was added in 2021 and removed again in 2022 🙂 Because all the visualizations had been migrated to a new code base using d3.js.

So we could even reopen this as a feature request...
