### ISSUE TITLE
Associations in Person View appear as a json string

### ISSUE THREAD

**Issue by brucejackson** [DavidMStraub/Gramps.js#22]
When viewing the Associatons tab for a Person, I expected to see a table listing the association.  For example,

| Name     | ID    | Association |
|----------|-------|-------------|
| Person 1 | I0001 | GodFather   |
| Person 2 | I0002 | Godmother   |

Instead a JSON string is shown.
![image](https://user-images.githubusercontent.com/1219029/125534548-e21d1123-f57e-47b9-a933-7a7564d80d38.png)

**Comment by DavidMStraub** [comment]
Oops! Seems I forgot to implement that and didn't notice it as I'm not using associations... One general problem with this is that it's currently not possible to fetch the required info of all associations of an object with a single API call.

**Comment by DavidMStraub** [comment]
> One general problem with this is that it's currently not possible to fetch the required info of all associations of an object with a single API call.

Turns out this statement was wrong. This should actually be easy to implement.

**Comment by DavidMStraub** [comment]
This should be fixed in `main` now! Would be great if you can confirm.

**Comment by brucejackson** [comment]
Hi David, Thanks, I will test both fixes this weekend and let you know the results

________________________________

**Comment by brucejackson** [comment]
Perfect.  Looks great
