### ISSUE TITLE
Some columns not sortable in lists view

### ISSUE THREAD

**Issue by lenzls** [DavidMStraub/Gramps.js#25]
Hello,

I've noticed that some columns are not sortable in the lists view.
Even though it looks like those are simple text based columns like others which are already sortable.

Not sortable for me are:
 - People → Given name
 - Families → Mother
 - Citations → Source: Title

Let me know if this is indeed something that should be fixed. I might give it a try then.

**Comment by DavidMStraub** [comment]
Good question; note that the sorting has to be done in the backend, as the items are only fetched page-wise. Can you please check the API docs on Swagger to see if the `sorted` keyword allows to sort by those fields? I don't remember, honestly. If not, we would have to fix it there.

**Comment by lenzls** [comment]
Oh, I haven't thought about, that all sorting is done server side. Still a small analysis of all the mentioned cases:

## People → Given name
Indeed, one can only sort on 

field | desc
-- | --
name | The sort name of the person
surname | The surname of the person, taking into consideration the given name and suffix for people who share the same surname

Even though I'm not exactly sure how both work, it looks like the given name is not included.

## Families → mother
Currently, when sorting on `father`, this is used:

Key | Description
-- | --
surname | The surname of the father or, if none present,  the mother of the family taking into consideration the given name and  suffix for families who share the same surname

And it seems there is no specific sort parameter which prefers the mother.

## Citations → Source: Title
There is no option to sort on the source title which comes from a nested resource anyway.


-----

All in all, Gramps.js can't really do anything in all the cases above. The webapi would need to support more fields to sort on.

I will close this issue.
