### ISSUE TITLE
Add UI for adding media references with image regions

### ISSUE THREAD

**Issue by DavidMStraub** [DavidMStraub/Gramps.js#50]
... e.g. to tag people in photos.

**Comment by brucejackson** [comment]
Will UI recognize existing face regions embedded in the metadata of uploaded images?  Similar to what like I tried to get with this https://github.com/gramps-project/addons-source/pull/478.

**Comment by DavidMStraub** [comment]
That's a cool idea. While it would be possible in principle to implement that fully client-side, I think it makes more sense to add this to the Web API reusing the existing Python code in the backend. Once we have a corresponding endpoint in the API (something like `/api/media/{handle}/facedetection/`), adding the UI would be straightforward.

**Comment by DavidMStraub** [comment]
Implemented basic tagging. For regions in metadata, we can add a separate regions once/if it's implemented in the backend.
