### ISSUE TITLE
Anniversary view:  NaN years ago

### ISSUE THREAD

**Issue by brucejackson** [DavidMStraub/Gramps.js#53]
If the date of any event is 'after' such as "(after 4 Nov 1994)" the view reports the event as occurring "NaN years ago" 

![image](https://user-images.githubusercontent.com/1219029/140386438-abbb9761-b671-412d-9db9-a5022df18772.png)

**Comment by DavidMStraub** [comment]
Oops :)

I think there are two problems; one is that I was assuming the date to be YYYY-MM-DD which is obviously not always the case. The second is that anniversaries don't even make sense for "after/before/about" dates. Not sure about "estimated/calculated".
